
export const SET_ALLIDS = 'SET_ALLIDS'
export const SET_ONEID = 'SET_ONEID'
export const ADD = 'ADD'
export const RESET_LIST = 'RESET_LIST'
export const SET_CREATED = 'SET_CREATED'
export const SET_DELETED = 'SET_DELETED'
export const SET_ERROR = 'SET_ERROR'
export const SET_SELECT_ITEMS = 'SET_SELECT_ITEMS'
export const SET_UPDATED = 'SET_UPDATED'
export const SET_VIEW = 'SET_VIEW'
export const SET_VIOLATIONS = 'SET_VIOLATIONS'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const SET_RETRIEVED = 'SET_RETRIEVED'
export const TOGGLE_MINI_LOADING = 'TOGGLE_MINI_LOADING'

export const SET_TOTAL_ITEMS = 'SET_TOTAL_ITEMS'
export const SET_PAGE = 'SET_PAGE'
